<!-- START of: content/help_asiakas_fi.phtml -->
<?php if ($this->resolver('content/help-tabs.phtml')): ?>
<?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help_asiakas'])?>
<?php endif; ?>
<div>
  <div class="sidebar left">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="mainbody right">
<?php if ($this->resolver('content/Additions/helpBegin.phtml')): ?>
<?=$this->render('content/Additions/helpBegin.phtml')?>
<?php endif; ?>
<h1>Asiakkaan opas</h1>

<div id="libcard" class="content-section">
<h2>Kirjastokortti ja PIN-koodi</h2>
  <p>Lainaamiseen tarvitset aina kirjastokortin. Henkilökohtaisen kirjastokortin ja PIN-koodin saat kaikista Keski-kirjastoista esittämällä kuvallisen henkilöllisyystodistuksen ja sitoutumalla kirjaston käyttösääntöihin (linkki puuttuu). Ensimmäinen kirjastokortti on maksuton, sen jälkeen annetusta kirjastokortista peritään maksu.</p>
  <p>Sama kirjastokortti käy kaikissa Keski-kirjastoissa. Kirjastokortin haltijana olet vastuussa kaikesta kortillasi lainatusta aineistosta. Alle 15-vuotiaan kirjastokortilla lainatusta aineistosta vastaa huoltaja. Kirjastokortin haltija sekä alle 15-vuotiaan kortinhaltijan takaaja sitoutuu korvaamaan vahingoittamansa, kadottamansa tai palauttamatta jättämänsä kirjastoaineiston.</p>
  <p>Alle 15-vuotiailta vaaditaan huoltajan allekirjoittama lomake kortin saamiseksi. Huoltajatiedot liitetään alle 15-vuotiaan asiakastietoihin.</p>
  <p>Halutessasi voit tulostaa Kirjastokortti-lomakkeen ja täyttää sen valmiiksi. Näin nopeutat asiointiasi kirjastossa. Samalla lomakkeella (toinen puoli) voi antaa Jyväskylässä alle 15-vuotiaalle luvan käyttää omatoimikirjastoja.</p>
    <p>Täytä ja tulosta: Kirjastokorttilomake (linkki puuttuu).</p>
  <p><b>Jos kirjastokorttisi katoaa</b>, ilmoita siitä viipymättä kirjastoon. Kun ilmoitus kadonneesta kortista on tehty, vastuusi kadonneella kortilla mahdollisesti tehdyistä lainoista päättyy. Kirjastosta saat uuden kirjastokortin (henkilöllisyystodistus mukaan). Samalla kun uusi kortti otetaan käyttöön, vanha kortti mitätöityy. Uuden kortin hinta on kuntakohtainen.</p>
  <p><b>Pidä yhteystietosi ajan tasalla</b>. Jos yhteystietosi muuttuvat, ilmoita muutoksesta kirjastoosi tai päivitä tietosi verkkokirjastossa. Nimenmuutoksen voit tehdä vain paikan päällä kirjaston asiakaspalvelussa. Ota mukaasi valokuvallinen henkilöllisyystodistus.</p>
  <p><b>PIN-koodi on nelinumeroinen luku</b>, jonka saat palveluaikana kaikista Keski-kirjastoista. Ota mukaan kirjastokorttisi ja kuvallinen henkilöllisyystodistus. PIN-koodi on monikäyttöinen. Tarvitset PIN-koodia, kun:</p>
  <ul class="list-bullets">
    <li>kirjaudut verkkokirjastoon</li>
    <li>lainaat kirjastossa lainausautomaatilla</li>
    <li>lainaat e-kirjoja ja e-äänikirjoja</li>
    <li>luet e-lehtiä</li>
    <li>asioit omatoimikirjastossa</li>
    <li>lainaat Hublet-tabletin (Jyväskylän pääkirjastossa ja Kuokkalan kirjastossa)</li></ul>
  <p>Jos unohdat PIN-koodisi, saat uuden kirjaston asiakaspalvelusta esittämällä kirjastokorttisi ja todistamalla henkilöllisyytesi. Sähköpostitse, puhelimitse tai chatin kautta PIN-koodia ei voida antaa johtuen tietoturvasyistä.</p>
</div>

<div id="loans-renewals" class="content-section">
<h2>Lainat ja uusiminen</h2>
  <p>Keski-kirjastojen kirjastokortti käy kaikissa Keski-kirjastoissa. Laina-ajoissa ja -rajoituksissa voi olla kirjastokohtaisia vaihteluja (mm. kirjastoautoilla). Lainojesi eräpäivät näet lainauskuitista tai verkkokirjaston Lainat –sivulta. </p>
  <p>Yleisimmin laina-ajat vaihtelevat viikosta neljään viikkoon:</p>
  <ul class="list-bullets">
     <li>4 viikkoa: Kirjat, äänitteet, nuotit, kielikurssit, CD-ROM-levyt, konsolipelit</li>
    <li>2 viikkoa: Aikakauslehdet, pikalainat, esineet, DVD- ja Blu-Ray-levyt</li>
    <li>1 viikko: Viikkolainat, kausikortit</li></ul>
  <p>Viimeistään eräpäivänä laina on palautettava kirjaston aukioloaikana, tai se on uusittava. Voit palauttaa lainasi mihin tahansa Keski-kirjastoon. Myöhässä palautetuista tai myöhässä uusituista lainoista peritään myöhästymismaksu. <a href=https://keski.finna-test.fi/Content/help_opac#renewals>Verkossa uusinta</a> on tehtävä ennen vuorokauden päättymistä. Lainoja voi uusia viisi kertaa, jos niistä ei ole varauksia. Viikkolainoja ja kausikortteja ei voi uusia.</p>
  <p>Joissakin Keski-kirjastoissa on käytössä palautusluukku. Lainojen palautus luukkuun tapahtuu lainaajan omalla vastuulla. Luukun kautta palautetut teokset rekisteröityvät palautetuiksi vasta seuraavana aukiolopäivänä.</p>
  <p>Kuvatallenteiden lainauksessa kirjastot noudattavat Mediakasvatus- ja kuvaohjelmakeskuksen asettamia ikärajoja. Kirjasto ei ole korvausvelvollinen, mikäli lainattu tallenne vahingoittaa asiakkaan laitteita.</p>
  <p>Menetät lainausoikeutesi kaikissa Keski-kirjastoissa, jos jätä lainat palauttamatta, maksut maksamatta tai turmelet kirjastoaineistoa.</p>
  <p>Voit saada ilmaiseksi sähköpostiisi muistutuksen lähestyvästä eräpäivästä 1-5 päivää ennen eräpäivää, jos ilmoitat sähköpostiosoitteesi kirjastoon tai tallennat sen omiin tietoihisi verkkokirjastossa. Eräpäivämuistutus on lisäpalvelu, jonka saapumatta jääminen esim. teknisen ongelman vuoksi ei poista velvollisuuttasi huolehtia lainojen uusimisesta tai palauttamisesta ennen eräpäivää. Olet itse vastuussa myös kertyneistä myöhästymismaksuista.</p>
</div>

<div id="holds" class="content-section">
<h2>Varaukset</h2>
  <p>Voit varata aineistoa verkkokirjaston kautta, puhelimitse tai kirjastossa asioidessasi. Varattu aineisto kuljetetaan haluamaasi toimipisteeseen. Varaaminen on ilmaista, mutta mikäli et nouda varaustasi viimeiseen noutopäivään mennessä, <b>peritään noutamattomasta varauksesta 2 euron maksu</b>. Kun noudat varauksesi, muistathan vielä lainata sen.</p>
  <p><b>Normaali varaus</b> (Varauksen kohde -valikosta: kunta) kohdistuu noutopaikaksi valitun kunnan kaikkien toimipisteiden aineistoon.
  <p><b>Seutuvaraus</b> (Varauksen kohde -valikosta: seutu) kohdistuu kaikkien Keski-kirjastojen aineistoihin ja se kuljetetaan valitsemaasi noutopaikkaan. Seutuvarauksen voi kohdistaa vain hyllyssä olevaan aineistoon. Seutuvarauksen voi kohdistaa vain aineistoon, jonka tila on <i>lainattavissa</i> verkkokirjastossa. Seutuvarauksella ei voi varata joidenkin kuntien lukioiden kirjoja eikä hankalasti kuljetettavia esineitä, kuten liikuntavälineet. Seutuvarauksen kuljettaminen valittuun noutopaikkaan kestää muutamasta päivästä yli viikkoon.</p>
  <p>Varauksen voi peruuttaa verkkokirjastossa, jos sitä ei ole vielä käsitelty eikä teos ole vielä kuljetuksessa tai noudettavissa. Jos varaus on ehditty jo käsitellä, onnistuu peruuttaminen ottamalla yhteyttä noutopaikaksi valittuun kirjastoon. Jos haet varauksen, mutta et haluakaan lainata sitä, palauta varaus kirjaston henkilökunnalle.</p>
  <h3>Noutoilmoitus saapuneesta varauksesta</h3>
  <ul class="list-bullets">
    <li>Saat kirjastosta noutoilmoituksen, kun varaamasi teos on noudettavissa kirjastossa. Varauksen viimeinen noutopäivä on kerrottu noutoilmoituksessa.</li>
    <li>Noutoilmoitus lähetetään valintasi mukaan joko sähköpostina, tekstiviestinä tai kirjeenä. Näet ilmoitustavan ja voit muuttaa sitä verkkokirjaston Omat tiedot -sivulla. Avaa lomake "Muuta viestiasetuksia" ja tee haluamasi muutokset.</li>
  </ul>
</div>

<div id="payments" class="content-section">
<h2>Maksut</h2>
  <p>Keski-kirjastoissa käytössä olevat maksut vaihtelevat kunnittain. Tiedot maksuista, myöhästymisilmoitusten lähettämisestä ja aineistojen korvaamisesta kerrotaan kunkin kirjaston internetsivuilla tai esitteissä.</p>
  <p>Kaikissa Keski-kirjastoissa:</p>
  <ul class="list-bullets">
    <li>10 euron velkasaldosta seuraa lainauskielto</li>
    <li>kerran vuodessa pienempikin velkasaldo on maksettava kokonaan</li></ul>
  <p>Näet verkkokirjastossa Maksut-sivulla mitä ja miksi asiointimaksuja on kertynyt. Maksuja otetaan vastaan kaikissa Keski-kirjastoissa riippumatta siitä, missä ne ovat syntyneet.
  <h3>Verkkomaksaminen</h3>
  <p>HUOM! TÄMÄ MUUTTUU VIELÄ! Voit maksaa verkossa maksusi, jotka ovat Hankasalmelta, Jyväskylästä, Jämsästä, Laukaasta, Luhangasta, Toivakasta, Uuraisilta tai Äänekoskelta. Muita kuntia on tulossa mukaan myöhemmin. Kuntakohtainen minimimaksu on 1,00 €. Omiin tietoihin täytyy olla merkittynä sähköposti. Palvelun tuottaa jyväskyläläinen Paytrail. </p>
</div>

<div id="interlibraryloans" class="content-section">
<h2>Kaukolainat</h2>
  <p><b><a href="https://webkake.kirjastot.fi/wtil/tilaa?pa_ulid=20" target="_blank">Tee kaukolainatilaus noudettavaksi Jyväskylästä.</a></b></p>
  <p><b><a href="https://webkake.kirjastot.fi/wtil/tilaa?pa_ulid=61" target="_blank">Tee kaukolainatilaus noudettavaksi Keuruulta.</a></b></p>
  <p><b><a href="<?=$this->url('feedback-form', ['id' => 'FeedbackIll'])?>">Muut Keski-kirjastot</a></b></p>
  <p>Kaukolainaksi voit tilata aineistoa, jota ei löydy Keski-kirjastoista. Kaukolainoja voit tilata koko Suomesta tai tarvittaessa ulkomailta. Tutustu oman kirjastosi kaukolainaohjeisiin ja lainoista perittäviin maksuihin. Kaukolainatilaus on sitova. Kaukolainoja tilataan vain kirjaston rekisteröityneille asiakkaille. </p>
  <p>Jokaisella Keski-kirjastolla on omat kaukolainasääntönsä ja maksunsa.</p>
  <p>Kaukolainasta peritään lainanantajakirjaston määrittelemä maksu ja mahdollinen kirjaston perimä tilausmaksu. Sitoudut tilauksen tehdessäsi maksamaan kaikki kaukolainasta aiheutuvat kulut. Maksu peritään lainaa noudettaessa. Noutamatta jätetystä kaukolainasta peritään 2 euron maksu ja aiheutuneet kulut, samoin jos perut tilauksesi ja laina on jo ennättänyt lähteä lainanantajakirjastosta. </p>
  <p>Yleensä kannattaa varautua n. 2 viikon odotukseen, mutta toimitusaika pitenee, esim. jos lähettävässä kirjastossa on varauksia samasta teoksesta. Kun kaukolainaksi tilattu teos saapuu kirjastoon, ilmoitetaan tilaajalle puhelimitse, sähköpostitse tai postitse.</p>
  <p>Kaukolainoissa noudatetaan lähettävien kirjastojen ehtoja ja laina-aikoja. Kaikkea materiaalia ei välttämättä anneta kaukolainaksi ja joskus lainan saa vain lukusalikäyttöön. </p>
  <p>Palauta kaukolaina siihen kirjastoon, josta olet sen noutanut. Kaukolainan uusintapyynnöt tehdään oman kirjaston kaukopalvelun kautta. </p>
</div>

<div id="hankintaehdotus" class="content-section">
<h2>Hankintaehdotus</h2>
  <p><b><a href="<?=$this->url('feedback-form', ['id' => 'AcquisitionRequest'])?>">Tee hankintaehdotus</a></b></p>
  <p>Otamme mielellämme vastaan hankintaehdotuksia, mutta kaikkea emme valitettavasti voi hankkia. Esimerkiksi moniin elokuvatallenteisiin ja e-kirjoihin ei ole myönnetty lainausoikeuksia, joten kirjastot eivät voi ostaa niitä kokoelmiinsa.</p>
  <p>Sen sijaan suurien suomalaisten kustantamojen uutuuskirjat hankitaan käytännössä katsoen kaikki, joten niitä ei tarvitse ehdottaa hankittaviksi. Hankintaprosessi saattaa kestää pitkäänkin, jopa kuukausia.</p>
  <p>Ennen hankintaehdotuksen lähettämistä varmista vielä verkkokirjastosta, että tarkoittamaasi teosta ei löydy Keski-kirjastojen kokoelmista. On hyvä myös tarkistaa, löytyykö teosta jo Keski-Suomen oppilaitosten tai korkeakoulujen kirjastojen kokoelmista.</p>
</div>
</div>
<!-- END of: content/help_asiakas_fi.phtml -->
