<!-- START of: Content/asiakkaana.fi.phtml -->

<? $this->headTitle('Info'); $this->content()->setHeading('Info'); ?>



<div class="row">
  <div class="col-sm-3 sidebar">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="col-sm-9">
    <div id="libcard" class="content-section">
      <h2>Kirjastokortti</h2>
      <img src="<?=$this->imageLink('keski_kortit.jpg');?>" style="float:right;margin-left: 15px;max-width: 40%;">
      <p>Lainaamiseen tarvitset aina kirjastokortin. Henkilökohtaisen kirjastokortin ja 
      tunnusluvun saat kaikista Keski-kirjastoista esittämällä kuvallisen
      henkilöllisyystodistuksen ja sitoutumalla kirjaston käyttösääntöihin. 
      Ensimmäinen kirjastokortti on maksuton, sen jälkeen annetusta kirjastokortista 
      peritään maksu. Sama kirjastokortti käy kaikissa Keski-kirjastoissa.
      Halutessasi voit tulostaa
<b><a href="<?= $this->fileSrc('Lainaajalomake.pdf')?>" target="blank">Lainaajatiedot-lomakkeen</a></b> ja täyttää sen valmiiksi. Näin nopeutat asiointiasi kirjastossa.
      Alle 18-vuotias saa kirjastokortin huoltajan kirjallisella suostumuksella.</p>


      <p>Kirjastokortin haltija on vastuussa kortillaan lainatusta aineistosta. 
      Alle 18-vuotiaan kirjastokortilla lainatusta aineistosta vastaa huoltaja.</p>


      <p>Jos korttisi katoaa, ilmoita siitä välittömästi kirjastoosi.
        <b><a href="<?= $this->fileSrc('Kayttosaannot_uusi.pdf')?>" target="blank">Kirjaston 
        käyttösääntöjen</a></b> mukaan kortin haltija vastaa kaikesta kortilla lainatusta 
        aineistosta siihen asti, kunnes katoamisilmoitus on tehty. </p>


      <h4>Pidä yhteystietosi ajan tasalla.</h4>
      <p>Jos puhelinnumerosi tai sähköpostiosoitteesi muuttuu, ilmoita muutoksesta 
      kirjastoosi tai päivitä tietosi verkkokirjaston Omat tiedot -sivulla. Nimenmuutoksen
      voit tehdä vain paikan päällä kirjaston asiakaspalvelussa. Ota mukaasi valokuvallinen
      henkilöllisyystodistus.</p>
      
    </div>
    <div id="pin" class="content-section">
        <h2>Tunnusluku</h2>
      <p>Tunnusluku on nelinumeroinen luku, jonka saat kaikista Keski-kirjastoista. 
      Ota mukaan kirjastokorttisi ja kuvallinen henkilöllisyystodistus.
      Tunnusluku on monikäyttöinen. Tarvitset tunnuslukua, kun:
      <ul class="list-bullets">
      <li>kirjaudut verkkokirjastoon</li>
      <li>lainaat kirjastossa lainausautomaatilla</li>
      <li>kirjaudut kirjastossa langattomaan verkkoon</li>
      <li>asioit omatoimikirjastossa</li>
      </ul>
      </p>
      <p>Jos unohdat tunnuslukusi, saat uuden kirjaston asiakaspalvelusta 
      esittämällä kirjastokorttisi lisäksi kuvallisen henkilöllisyystodistuksen. 
      Sähköpostitse tai puhelimitse tunnuslukua ei voida antaa johtuen 
      tietoturvasyistä. </p>
    </div>
    <div id="asclient" class="content-section">
      <h2>Asiointi verkkokirjastossa</h2>
<p>Verkkokirjastoa voi käyttää ilman kirjautumista. Monet palvelut, kuten lainojen uusiminen ja omien tietojen hallinnointi, onnistuvat kuitenkin vain 
kirjautumalla palveluun kirjastokortin numerolla ja 4-numeroisella tunnusluvulla. Ensimmäinen kirjautuminen luo automaattisesti verkkokirjaston käyttäjätilin, 
minkä jälkeen kirjautuneen käyttäjän palvelut ovat automaattisesti käytettävissäsi.</p>

<h4>Kirjautuminen</h4>
<p>Löydät kirjautumispainikkeen oikeasta yläkulmasta verkkokirjaston jokaiselta sivulta. Pienemmillä näytöillä kirjautumispainike voi näkyä pelkkänä henkilökuvakkeena, 
minkä lisäksi se löytyy pudotusvalikosta. Kun olet kirjautunut sisään, muuttuu kirjautumispainike henkilökuvakkeeksi. Näytön koosta riippuen näet kuvakkeen vieressä 
tällöin myös oman nimesi.</p>

<h4>Käyttäjätili</h4>
<p>Ensimmäinen kirjautuminen luo sinulle automaattisesti oman käyttäjätilin ja liittää siihen kirjastokorttisi tiedot. 
Käyttäjätiliin tallentuvat tekemäsi suosikkilistat, uutuusvahdit ja mahdolliset linkittämäsi kirjastokortit. </p>

<p>Mikäli et kirjaudu verkkokirjastoon vuoteen, poistuu käyttäjätilisi ja sen mukana peruuttamattomasti myös suosikkilistat, 
uutuusvahdit ja linkitetyt kirjastokortit. Kirjastokortti toimii kuitenkin edelleen sekä kirjastossa että verkkokirjastoon kirjautumisessa. 
Seuraavalla kirjautumisella verkkokirjasto luo uuden käyttäjätilin, jolloin voit perustaa uudet suosikkilistat ja uutuusvahdit sekä linkittää 
haluamasi kortit uudelleen tiliisi.</p>

<p>Ennen käyttäjätilisi poistumista saat sähköpostiisi varoituksen, jolloin voit vielä estää tilisi 
vanhenemisen kirjautumalla verkkokirjastoon.</p>


<h4>Omat palvelut</h4>
<p>Kirjautumisen jälkeen saat käyttöösi monta hyödyllistä palvelua. Voit uusia lainasi, tehdä varauksia, tarkastella maksutietojasi, vaihtaa tunnuslukusi ja 
tarvittaessa päivittää yhteystietosi. Voit myös luoda suosikkilistoja ja uutuusvahteja. 
Kun olet kirjautuneena, löydät kaikki palvelut yläpalkin pudotusvalikosta.</p>

<p>Verkkokirjaston käyttäjätiliin on mahdollista liittää useampia kirjastokortteja, minkä jälkeen voit yhdellä kirjautumisella 
uusia vaikka koko perheen lainat. Palvelua voi käyttää, jos tiedossa on liitettävän kortin numero ja tunnusluku. Kaikille käyttäjätiliin liitetyille 
kirjastokorteille voi antaa myös nimen.</p>

<h4>Uloskirjautuminen</h4>
<p>Kun haluat kirjautua ulos palvelusta, klikkaa ensin yläpalkissa näkyvää henkilökuvaketta ja valitse pudotusvalikosta ”Kirjaudu ulos”. </p>
      
      
      
    </div>
    <div id="loans-renewals" class="content-section">
       <h2>Lainat ja uusiminen</h2>
      <p>Lainojesi eräpäivät näet lainauskuitista tai verkkokirjaston Lainat –sivulta. 
      Viimeistään eräpäivänä laina on palautettava kirjaston aukioloaikana, tai se on 
      uusittava. Verkossa uusinta on tehtävä ennen vuorokauden päättymistä.  
      Voit palauttaa lainasi mihin tahansa Keski-kirjastoon. Myöhässä palautetuista tai 
      uusituista lainoista peritään myöhästymismaksu. </p>
      <p>Joissakin Keski-kirjastoissa on käytössä palautusluukku. Lainojen palautus 
      luukkuun tapahtuu lainaajan omalla vastuulla. Luukun kautta palautetut teokset 
      rekisteröityvät vasta seuraavana aukiolopäivänä. </p>
      <h4>Uusi lainasi verkkokirjastossa</h4>
      <p>Kirjaudu verkkokirjastoon ja valitse yläpalkin pudotusvalikosta sivu "Lainat". Jos kirjauduit verkkokirjaston etusivulta, 
      avautuu sivu automaattisesti. </p>
            <p>Valitse rastittamalla uusittavat lainat ja klikkaa painiketta "Uusi valitut lainat". 
      Voit uusia lainasi kolme kertaa, mikäli niihin ei kohdistu varauksia.
      Voit uusia lainasi myös soittamalla omaan kirjastoosi. 
      Yhteystiedot ja aukioloajat löydät etusivulta ja kohdasta "Kirjastot". </p>
      
      <h4>Laina-aika ja lainamäärärajoitukset</h4>
      <p>Laina-aika on yleensä 28 vuorokautta. Seuraavilla aineistoilla laina-aika 
      on 14 vuorokautta:</p>
        <ul class="list-bullets">
            <li>aikakauslehdet</li>
            <li>DVD- ja Blu-ray –levyt</li>
            <li>konsolipelit</li>
            </ul>
            
        <p>E-kirjat ja e-äänikirjat ovat sähköistä aineistoa. Niiden laina-aika on 7 tai 
        14 vuorokautta. Muissa aineistoissa voi olla yksilöllisiä laina-aikoja.</p> 
        <p>E-kirjojen lainamäärää voidaan rajoitta, ja rajoitukset vaihtelevat palveluittain. 
        Myös konsolipelien määrää on rajoitettu. Asiakkaalla voi olla lainassa enintään 5 
        konsolipeliä samanaikaisesti.</p>

      <h4>Kirjaston ilmoitukset apunasi</h4>
      <ul class="list-bullets">
      <li>Eräpäivämuistutukset lähetetään aina sähköpostitse. Voit valita, lähetetäänkö 
      viesti 1,2,3,4 tai 5 päivää ennen eräpäivää.</li>
      <li>Myöhästymisilmoitukset lähetetään joko sähköpostitse, tekstiviestinä tai kirjeenä. 
      Ns. toinen ilmoitus lähtee kuitenkin aina kirjeenä.</li>
      <li>Voit muokata omia ilmoitusasetuksiasi verkkokirjaston Omat tiedot -sivulla. Avaa lomake 
      "Tee viestiasetusten muutospyyntö". Tieto välityy kirjaston henkilökunnalle, 
      joka tekee muutokset asiakastietoihisi.</li>
      <br>
      </ul>
    </div>
    <div id="holds" class="content-section">
      <h2>Varaukset</h2>
      <p>Varausten tekeminen ja niiden hallinnointi onnistuu kätevimmin verkkokirjastossa. 
      Tee ensin tiedonhaku. Voit tehdä varauksen joko suoraan hakutuloksista tai 
      klikkaamalla teoksen nimeä ja siirtymällä teostiedot -sivulle. Klikkaa 
      Varaa -painiketta ja valitse, mistä kirjastosta haluat noutaa teoksen.
      Voit määritellä ensisijaisen noutopaikan verkkokirjaston Omat tiedot -sivulla. 
      Tämän jälkeen palvelu valitsee tämän kirjaston oletuksena. Ensisijaisen noutopaikan 
      voi kuitenkin aina ohittaa ja valita noutopaikan itse. </p>
      <p>Jos et vielä ollut kirjautunut sisään, pyytää järjestelmä sinua kirjautumaan 
      tässä vaiheessa.
 <p>Varaus on maksuton. Noutamattomasta varauksesta peritään maksu. Varattu teos voi 
 tulla mistä tahansa Keski-kirjastosta. Huomaathan, että samaan teokseen voi tehdä 
 vain yhden varauksen kerrallaan</p>
 
 <p>Varauksen noutoaika on normaalisti seitsemän päivää. Kirjastoautoissa noutoaika on kuitenkin 
 pidempi autojen erilaisista aikatauluista johtuen.</p>
 
      <p>Varauksen voi peruuttaa verkkokirjastossa, jos sitä ei ole vielä käsitelty 
      eikä teos ole vielä matkalla tai noudettavissa.
          Jos varaus on ehditty jo käsitellä, onnistuu peruuttaminen ottamalla 
          yhteyttä noutopaikaksi valittuun kirjastoon.</p>

      <h4>Noutoilmoitus saapuneesta varauksesta</h4>
      <ul class="list-bullets">
      <li>Saat kirjastolta noutoilmoituksen, kun varaamasi teos on noudettavissa kirjastossa. 
      Varauksen viimeinen noutopäivä on kerrottu noutoilmoituksessa.</li>
      <li>Noutoilmoitus lähetetään valintasi mukaan joko sähköpostina, tekstiviestinä 
      tai kirjeenä. Näet ilmoitustavan ja voit muuttaa sitä verkkokirjaston Omat tiedot -sivulla. 
      Avaa lomake "Tee viestiasetusten muutospyyntö" ja tee haluamasi muutokset. Tieto välityy kirjaston 
      henkilökunnalle, joka tekee toivomasi muutokset asiakastietoihisi.</li>
      <li>Huomioithan, että kirjeitse lähetettävät saapumisilmoitukset voivat joissain 
      tapauksissa saapua kovin lähellä viimeistä noutopäivää.</li>
      </ul>
      
      <p>Jos et halua hyödyntää verkkokirjastoa varauksen tekemisessä, onnistuu 
      varauksen tekeminen myös ottamalla yhteyttä kirjaston asiakaspalveluun.</p>
    </div>
    <div id="payments" class="content-section">
      <h2>Maksut</h2>
      <p>Verkkokirjastossa näkyvät maksut eivät sisällä mahdollisia maksuja aineistosta, 
      jota ei ole palautettu.
       </p>
      <p>
    <b><a href="<?= $this->fileSrc('Maksuliite_2017.pdf')?>" target="blank">Maksut ja korvaukset</a></b>. 
          </p>
    </div>
    <div class="grid_18">
    <div id="favoritenew" class="content-section">
      <h2>Suosituimmat uutuudet</h2>
      <p>Viikkolaina-kokoelma Keski-kirjastoissa sisältää lähinnä suosittuja uutuuksia. 
      Viikkolainojen avulla halutaan varmistaa, että asiakkaat voivat saada myös uutuuskirjoja 
      suoraan hyllystä ilman varaamista.
      Viikkolaina-aineistolla on lyhyempi laina-aika (7 vrk), niitä ei voi uusia eikä varata. 
      Viikkolaina-aineistoa voi olla kirjastossa saatavilla, vaikka teoksesta olisi useitakin 
      varauksia.</p>
    </div>
    <div id="newitems" class="content-section">
        <a name="Uutuusvahtiankkuri"></a>
      <h2>Uutuusvahti</h2>

      <p>Verkkokirjasto tallentaa väliaikaisesti kaikki hakusi, vaikka et olisikaan kirjautuneena. 
         Välimuistin tyhjentäminen tai selaimen sulkeminen poistaa nämä tallennetut tiedot.
      Viimeisimmät haut löydät verkkokirjaston sivulta "Uutuusvahti". </p>
      
     <p>Voit tallentaa haun pysyvästi painamalla tallenna-painiketta (plus-merkki) haun vieressä. 
      Jos haluat saada tiedon haun mukaisista uutuuksista sähköpostiisi, on haku muutettava vielä uutuusvahdiksi. 
      Oletuksena haun kohdalla olevassa pudotusvalikossa on "ei mitään", mutta vaihtamalla valinnaksi
      "päivittäin" tai "viikottain" tallentuu haku uutuusvahdiksi ja saat tiedon uutuuksista sähköpostiisi. 
      Uutuusvahdin sähköpostiosoite on annettava erikseen Omat tiedot -sivulla. 
      </p>
    </div>
    <div id="favoritelists" class="content-section">
         <a name="Suosikkilistatankkuri"></a>
      <h2 id ="suosikkiohje">Suosikkilistat</h2>
      <p>
    Voit luoda itsellesi verkkokirjastossa yhden tai useamman suosikkilistan ja tallentaa niihin vaikka parhaat lukemasi kirjat 
    tai listan kirjoista, jotka haluat vielä lukea. Löydät kaikki suosikkilistasi ja voit luoda uusia listoja kirjautumalla verkkokirjastoon 
    ja valitsemalla pudotusvalikosta sivun "Suosikit". Jos listat ovat piilossa, saat ne näkyville klikkaamalla pientä nuolta navigaatiossa sanan "Suosikit" vieressä. 
    Mobiilinäytössä listat löytyvät näytön alaosan valikon kautta.</p>
    
    <p>Suosikkilistalle on annettava nimi, mutta voit kirjoittaa myös pidemmän kuvauksen listasta. 
    Jokaisen teoksen kohdalla on lisäksi tilaa omille muistiinpanoille. Listat ovat oletuksena yksityisiä, mutta voit halutessasi julkaista ne 
    ja jakaa saamasi osoitteen vaikka sosiaalisessa mediassa tai sähköpostin kautta. Pelkkä julkaiseminnen ei vielä tuo listaa näkyväksi muille käyttäjille.</p>
    <p>Teoksen lisääminen suosikkilistalle on helppoa. Kirjaudu verkkokirjastoon ja tee haku. Paina teoksen vieressä olevaa "nastaa" ja valitse 
    pudotusvalikosta lista, johon haluat lisätä teoksen. 
    
    </p>

      
    </div>
    <div id="interlibraryloans" class="content-section">
     <h2>Kaukolainat</h2>
        <p><b><a href="https://webkake.kirjastot.fi/wtil/tilaa?pa_ulid=20" target="_blank">Kaukopalvelutilaus</a></b></p>
        
        <p>Kaukopalvelu on kirjastojen välistä toimintaa, ja sen avulla voit hyödyntää 
        koko kirjastoverkkoa. Jos missään Keski-kirjastossa ei ole haluamaasi teosta, 
        se voidaan tilata muualta kaukopalvelun kautta. Keski-kirjastojen kokoelmissa 
        olevia, mutta lainassa olevia teoksia ei tilata kaukolainana - tee tällöin 
        normaalisti varaus teoksesta. Kun teos on noudettavissa, 
        saat siitä noutoilmoituksen.</p>
         
        <p>Kaukopalvelutilauksia otetaan vastaan kaikissa Keski-kirjastoissa.</p>
         
        <h5>Kaukolainat ovat maksullisia.</h5>
         
        <p>Kirjastot perivät kaukolainoista lähettävien kirjastojen maksujen lisäksi 
        tilausmaksun. Maksut peritään lainojen saavuttua. Lisäksi tilaaja sitoutuu 
        suorittamaan posti-, jäljenne- ym. kulut.</p>
         
        <h5>Toimitusajat vaihtelevat.</h5>
         
        <p>Yleensä kannattaa varautua n. 2 viikon odotukseen, mutta toimitusaika pitenee 
        esim. jos lähettävässä kirjastossa on varauksia samasta teoksesta. 
        Kun kaukolainaksi tilattu teos saapuu kirjastoon, ilmoitetaan tilaajalle 
        puhelimitse, sähköpostitse tai postitse. </p>
         
        <h5>Kaukolainoissa noudatetaan lähettävien kirjastojen ehtoja ja laina-aikoja.</h5>
         
        <p>Kaikkea materiaalia ei välttämättä anneta kaukolainaksi ja joskus lainat 
        saa vain lukusalikäyttöön.</p>
         
        <h5>Kaukolainat palautetaan aina tilaajakirjaston kautta.</h5>
         
        <p>Lainan mukana säilytettävään saateliuskaan on merkitty eräpäivä, 
        jolloin laina tulee palauttaa takaisin kaukopalveluun. Myös uusintapyynnöt 
        tehdään kaukopalvelun kautta.</p>
        
        <h5>Kaukopalvelu kirjastoille</h5>
        <p>Lähetämme kirjastoille kaukolainaksi aineistoa, 
        jota ei ole niiden omissa kokoelmissa. Kaukolainatilauksen voi tehdä suoraan 
        Keski-verkkokirjaston kautta tai ottamalla sähköpostitse yhteyttä siihen 
        Keski-kirjastoon, jonka kokoelmiin materiaali kuuluu. Kaikkien Keski-kirjastojen 
        yhteystiedot löytyvät Kirjastot-sivulta. </p>
    </div>
    
    
 <div id="hankintaehdotus" class="content-section">
      <h2>Hankintaehdotus</h2>
<p><b><a href="https://www.keskikirjastot.fi/web/arena/acqusition-suggestion" target="_blank">Hankintaehdotus</a></b></p>


<p>Otamme mielellämme vastaan hankintaehdotuksia, mutta kaikkea emme valitettavasti voi hankkia. Esim. moniin elokuvatallenteisiin ja e-kirjoihin ei ole myönnetty lainausoikeuksia, 
joten kirjastot eivät voi ostaa niitä kokoelmiinsa.</p>
 
<p>Sen sijaan suurien suomalaisten kustantamojen uutuuskirjat hankitaan käytännössä katsoen kaikki, joten niitä ei tarvitse ehdottaa hankittaviksi. 
Voit varata aineiston heti, kun se näkyy verkkokirjastossa. Hankintaprosessi saattaa kestää pitkäänkin, jopa kuukausia.</p>
 
<p>Ennen hankintaehdotuksen lähettämistä varmista vielä Keski-verkkokirjastosta, että tarkoittamaasi teosta ei löydy Keski-kirjastojen kokoelmista. </p>
<p>Huom. Varauksen tekeminen onnistuu vain, jos ehdottamasi teos hankitaan kirjastoon.</p>
<p>On hyvä myös tarkistaa, löytyykö teosta jo Keski-Suomen oppilaitosten tai korkeakoulujen kirjastojen kokoelmista. </p>

</div>

<div id="omatoimikirjastot" class="content-section">
    <h2>Omatoimikirjastot</h2>
    <p>Omatoimikirjasto tarkoittaa kirjaston laajennettuja aukioloja ilman henkilökuntaa. Kirjastoon pääsee sisään kirjastokortilla ja PIN-koodilla aikaisemmin aamulla, iltaisin ja viikonloppuisin tai vaikka juhlapyhinä, vaikka henkilökuntaa ei olisi paikalla. 
    <p>PIN-koodi on sama, jota käytät täällä verkkokirjastossa. Jos PIN-koodia ei ole, se on haettava henkilökohtaisesti jostain Keski-kirjastosta palveluaikana.</p>

<p>Kirjastossa voi omatoimiaikana lainata ja palauttaa aineistoa sekä lukea lehtiä, käyttää internetiä tai oleskella ja opiskella. Usein myös kopiokone ja tulostin ovat asiakkaiden käytössä. Maksuja ei voi maksaa kuin palveluaikoina, mutta osalla kunnista on käytössä verkkomaksumahdollisuus. 
Omatoimikirjaston käyttäjän tulee osassa kunnista olla yli 15-vuotias, lapset pääsevät sisään vanhempien seurassa. Alle 15-vuotiaiden itsenäinen pääsy voi onnistua sopimuksella. Kysy lisää omasta kunnastasi.</p>
</div>

 <div  id="accessibility" class="content-section">
            <h2>Esteettömyys</h2>
                <h3>Kotipalvelu</h3>
                    <p>Osa Keski-kirjastoista tarjoaa kotipalvelua, jolla tarkoitetaan kirjastoaineiston tuomista asiakkaalle kotiin. Kotipalvelu on tarkoitettu niille asiakkaille, jotka eivät korkean iän, sairauden, tai toimintakyvyn heikentymisen vuoksi pysty itse asioimaan kirjastossa.</p>
                    <p>
                    Ennen palvelun aloittamista asiakas haastatellaan. Sen perusteella kirjastovirkailija valitsee asiakkaalle lukemista, musiikkia, äänikirjoja, tms.
                    Kotipalveluasiakasta koskevat kirjaston käyttösäännöt.
                    </p>
                    <p>Palvelu on maksutonta.</p>
                    <p>Lisätietoja saat omasta kirjastostasi.
                    </p><br>
                <h3>Celia-kirjaston palvelut</h3>
                    <p>Celian äänikirjat on tarkoitettu henkilöille, 
                    joilla on lukemisen este, esim. heikentynyt näkö tai lukivaikeus.</p>
                    <p>Osassa kirjastoja voi rekisteröityä <a href="https://www.celia.fi/" target="_blank">Celia-verkkopalvelun</a>
                    tai Celian cd-kerhopalvelun käyttäjäksi. Lisäksi osalla Keski-kirjastoja on kokoelmissaan Celian cd-äänikirjoja, 
                    joita lukemisesteiset voivat lainata Keski-kirjastokortilla.</p><br>
                <h3>Viittomakielinen kirjasto</h3>
                    <p><a href="http://www.viittomakielinenkirjasto.fi/" target="_blank">Viittomakielinen kirjasto</a>
                    on Kuurojen liiton ylläpitämä verkkopalvelu, johon kootaan 
                    viittomakielistä aineistoa. Kirjasto tallentaa Suomen viittomakielisten 
                    kulttuuria, historiaa ja kieltä. Aineisto on helposti kaikkien 
                    saatavilla eikä asiakkuus vaadi rekisteröitymistä. Osa materiaalista on 
                    käännetty suomeksi tai ruotsiksi. </p>
    </div>

    <div id="userrights" class="content-section">
      <h2>Keski-kirjastojen käyttösäännöt</h2>
      <p>Vastaanottaessasi kirjastokortin sitoudut noudattamaan Keski-kirjastojen käyttösääntöjä.
      Käyttösääntöihin voit tutustua tästä <b><a href="https://www.keskikirjastot.fi/web/arena/kayttosaannot" target="blank">linkistä</a></b>.
      </p>

      </div>
     <div id="kokoelmalinjaus" class="content-section">
      <h2>Keski-kirjastojen kokoelmalinjaus</h2>
      <p>
          Keski-kirjastojen palvelujen perustana on yhteiskäyttöinen, riittävän laaja, helposti löydettävä ja asiantuntevasti hoidettu kokoelma, 
          joka muodostuu yksittäisten kirjastojen kokoelmista. Keski-kokoelma rakentuu yhteistyölle ja se laajentaa yksittäisten kirjastojen kokoelmia ja palveluja.</p>


</div>

<div id="vaski" class="content-section">
    <h2>Mikä Keski?</h2>
    <p>Keski-kirjastot on 23 keskisuomalaisen kunnan yhteistoimintaa. Keski-kirjastoihin kuuluu siis kaikki Keski-Suomen maakunnan yleiset kirjastot. 
    Keski-kirjastoilla on yli 50 toimipistettä ja useita kirjastoautoja. 
    Keski-kirjastoilla on yhteinen tietokanta, josta voi etsiä aineistoa ja tehdä varauksia, koska kaikki kirjastot käyttävät samaa kirjastojärjestelmää. 
    Kirjastojen välillä toimii säännölliset kuljetukset. Yhteistyö mahdollistaa:</p>
    <img src="<?=$this->imageLink('Keski-kirjastot_kompaktilogo_rgb.jpg');?>" style="float:right;margin-left: 15px;max-width: 30%;">
    <ul class="list-bullets">
        <li>yhteisen kirjastokortin</li>
        <li>yhteisen kokoelman</li>
        <li>yhteiset käyttösäännöt</li>
        <li>maksuttomat aineistokuljetukset</li>
        <li>yhteiset e-aineistot</li>
    </ul>
    <p>Käytännössä tämä tarkoittaa sitä, että voit asioida kaikissa Keski-kirjastoissa
    yhtä kirjastokorttia käyttämällä. Jos haluamasi aineisto löytyy toisen Keski-kunnan kokoelmasta, voit tilata sen maksutta omaan kirjastoosi.</p>
    <p>Voit palauttaa lainaamasi aineiston mihin tahansa Keski-kirjastoon. Keski-asiakkaana sinulla on koko alueen kokoelma käytettävissäsi.</p>

</div>

 <div id="vaskilibraries" class="content-section">
    <h2>Keski-kirjastot ja kunnat</h2>
    <div class="kirjastolista row">
    <div class="col-xs-12">
        <p>Keski on 23 kunnan kirjastoyhteistyö. Keski-kirjastoilla on käytössään 
        yhteinen kokoelma ja seutuvaraukset. Voit käyttää Keskin kirjastokorttia kaikissa 
        näissä kunnissa ja palauttaa lainasi mihin tahansa Keski-kirjastoon. </p>


 <p>Keski-kirjastoyhteistyöhön kuuluvat kirjastot:</p>

    </div>
    <div class="col-sm-5 col-xs-12">
<ul class="list-bullets">
       <li>1 Jyväskylän kaupunginkirjasto</li>
<li>2 Hankasalmen kunnankirjasto</li>
<li>3 Joutsan kunnankirjasto</li> 
<li>4 Jämsän kaupunginkirjasto</li>
<li>5 Kannonkosken kunnankirjasto</li>
<li>6 Karstulan kunnankirjasto</li>
<li>7 Keuruun kaupunginkirjasto</li>
<li>8 Kinnulan kunnankirjasto</li>
<li>9 Kivijärven kunnankirjasto</li>
<li>10 Konneveden kunnankirjasto</li>
<li>11 Kuhmoisten kunnankirjasto</li>
<li>12 Kyyjärven kunnankirjasto</li>
<li>13 Laukaan kunnankirjasto</li>
<li>14 Luhangan kunnankirjasto</li>
<li>15 Multian kirjasto</li>
<li>16 Muuramen kunnankirjasto</li>
<li>17 Petäjäveden kunnankirjasto</li>
<li>18 Saarijärven kaupunginkirjasto</li>
<li>19 Toivakan kunnankirjasto</li>
<li>20 Uuraisten kunnankirjasto</li>
<li>21 Wiitaunionin aluekirjasto (Viitasaari & Pihtipudas)</li>
<li>22 Äänekosken kaupunginkirjasto</li>
          </ul>
 
    </div>
        <div class="col-sm-4 col-xs-6">
            <img src="<?=$this->imageLink('Keski-kirjastot-kartalla.jpg');?>" style="float:right;margin-left: 5px">
    </div>    

</div>







  </div>
</div>




<!-- END of: Content/asiakkaana.fi.tpl -->


