<? $this->headTitle($this->transEsc("events_page_title")); ?>
<!-- Events -->
<div class="events-page">
    <div class="events-container">
        <div class="event-filters">
            <h2 class="sr-only">Tapahtumien rajaus</h2>
            <button id="toggleEventFilters" class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Rajaa tapahtumia
            </button>
            <div class="collapse" id="collapseExample">
                <div class="event-filter-container event-tags-filter">
                    <fieldset class="event-tags-fieldset">
                        <legend><h3 class="event-category-filter-title">Kategoria</h3></legend>
                    </fieldset>
                </div>
                <div class="event-filter-container event-location-filter">
                    <fieldset class="event-locations-fieldset">
                        <legend><h3 class="event-location-filter-title">Sijainti</h3></legend>
                    </fieldset>
                </div>
            </div>

        </div>
        <div class="keski-events-archive" id="keskiEvents">
            <h1 class="events-section-title">Tapahtumat</h1>
            <ul id="keskiEventsUl">
                <li class="event-li no-matching-events" style="display: none">
                    <div class="no-matching-events-div">
                        <p>Valituilla hakuehdoilla ei löytynyt yhtään tapahtumaa</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Events modal -->
<div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="eventModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="eventModalTitle">Event</h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="eventModalBody" class="modal-body">
                <div id="eventDescription"></div>
                <div id="mapRow" class="">
                    <div id="eventMapContainer" class=""></div>
                </div>
                <div id="eventImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary close-event-modal" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
</div>
