<!-- START of: finna - search/browsebar.phtml -->
<div class="browsebar">
    <div class="container">
<div class="browse-link text-center"><a href="/beta/OrganisationInfo"><i class="iconlabel format-1placeplace"></i><?=$this->transEsc('browsebar_kirjastot')?></a></div>
        <nav class="navbar">
            <span class="browsebar-title"><?=$this->translate('Browse')?></span>
            <div class="wrapper resize-drag nav-wrapper">
                <ul class="nav navbar-nav nav-ul">
                    <li><a class="iconlabel format-1bookbook" href="MyResearch/CheckedOut"><?=$this->transEsc("browsebar_omatlainat")?></a></li> 
                    <li><a class="iconlabel format-1bookbook" href="Search/Results?lookfor=&type=AllFields&filter%5b%5d=first_indexed%3A%22%5bNOW-1MONTHS+TO+NOW%5d%22"><?=$this->transEsc("browsebar_uutuudet")?></a></li> 
                    <li><a class="iconlabel format-1videovideo" href="Search/Results?type=AllFields&amp;filter%5B%5D=~format%3A%220%2FVideo%2F%22"><?=$this->transEsc("format_Video_plural")?></a></li>
                    <li><a class="iconlabel format-ebook" href="Search/Results?filter%5B%5D=~genre_facet%3A%22E-kirjat%22&type=AllFields"><?=$this->transEsc("browsebar_ematerial")?></a></li>
                    <li><a href="Search/Results?limit=0&filter%5B%5D=%7Egenre_facet%3A%22Lastenkirjallisuus%22&filter%5B%5D=%7Egenre_facet%3A%22Nuortenkirjallisuus%22&type=AllFields"><i class="fa fa-child" aria-hidden="true"></i> <?=$this->transEsc("browsebar_children");?></a></li>
                    </ul>
            </div>
        </nav>
    </div>
</div>
<!-- END of: finna - search/browsebar.phtml -->