<!-- START of: finna - search/home/home-1.phtml -->
<div class="frontpage-info-msg"><?= $this->transEsc("front_page_msg") ?></div>
<div class="row home-first-row">
    <div class="col-sm-5 col-md-push-7">
        <div class="lib-home-container">
            <h2 class="title-underlined-wide news-section-title"><?= $this->transEsc("organisation_info_schedules") ?></h2>
            <iframe title="Aukioloajat" allowfullscreen="" frameborder="0" height="760" id="libFrame" referrerpolicy="unsafe-url" scrolling="no"
            src="https://olli-suutari-jkl.github.io/jyvaskyla.fi.kirjasto/pages/homePageWeek.html?lib=85159&amp;consortium=2113&amp;lang=fi&amp;homePage=true&amp;libPageUrl=https://keski.finna.fi/Content/kirjastot&amp;primary=00446B&amp;btnHover=002438" width="100%" style="display: none; height: 340px" onload="this.style.display='block';" ></iframe>
        </div>
    </div>
    <div class="col-sm-7 col-md-pull-5">
        <div class="keski-news-home" id="keskiNews">
            <h2 class="title-underlined-wide news-section-title"><?= $this->transEsc("news_section_title") ?></h2>
            <ul id="keskiNewsUl"></ul>
            <div class="news-page-link-container">
                <a role="menuitem" href="/Content/uutiset" class="news-page-link btn btn-primary">
                    <span class="news-archive-text">
                        <?= $this->transEsc("to_news_archive") ?>
                   </span>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- News modal -->
<div class="modal fade" id="newsModal" tabindex="-1" role="dialog" aria-labelledby="newsModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="newsModalTitle"></h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div id="newsModalBody" class="modal-body">
                <div id="newsDescription"></div>
                <div id="newsImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary close-news-modal" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
</div>
<!-- END of: finna - search/home/home-1.phtml -->