<!-- START of: finna - search/home/home-1.phtml -->
<div class="row home-first-row">
    <div class="col-sm-5 col-md-push-7">
        <div class="lib-home-container"></div>
    </div>
    <div class="col-sm-7 col-md-pull-5">
        <div class="keski-news-home infobox" id="keskiNews">
            <h2 class="news-section-title"><?= $this->transEsc("news_section_title") ?></h2>
            <ul id="keskiNewsUl"></ul>
            <p class="news-page-link-container">
                <span class="news-date" aria-hidden="true"></span>
                <a class="news-page-link" href="/Content/uutiset">
                        <span class="news-li-title"><?= $this->transEsc("to_news_archive") ?>
                            <i class="fa fa-arrow-circle-o-right"></i></span>
                </a>
            </p>
        </div>
    </div>
</div>
<script>
    // Add the library home schedules.
    var libLang = document.documentElement.lang;
    if (libLang !== "fi") {
        libLang = "en";
    }
    $('.lib-home-container').append('<iframe allowfullscreen="" frameborder="0" height="360" id="libFrame" referrerpolicy="unsafe-url" scrolling="no" src="https://olli-suutari-jkl.github.io/jyvaskyla.fi.kirjasto/pages/homePage.html?lib=85159&amp;consortium=2113&amp;lang=' + libLang + '&amp;homePage=true&amp;libPageUrl=https://keski.finna-test.fi/Content/kirjastot&amp;primary=414141&amp;btnHover=9F230C" width="100%" style="height: 320px;"></iframe>');
</script>
<!-- END of: finna - search/home/home-1.phtml -->