<!-- START of: finna - search/home/home-1.phtml -->
<div class="frontpage-info-msg"><?= $this->transEsc("front_page_msg") ?></div>
<div class="row home-first-row">
    <div class="col-sm-5 col-md-push-7">
        <div class="lib-home-container">
            <iframe title="Opening hours" allowfullscreen="" frameborder="0" height="360" id="libFrame" referrerpolicy="unsafe-url" scrolling="no" src="https://olli-suutari-jkl.github.io/jyvaskyla.fi.kirjasto/pages/homePage.html?lib=85159&amp;consortium=2113&amp;lang=en&amp;homePage=true&amp;libPageUrl=https://keski.finna-test.fi/Content/kirjastot&amp;primary=414141&amp;btnHover=9F230C" width="100%" style="display: none; height: 340px" onload="this.style.display='block';" ></iframe>
        </div>
    </div>
    <div class="col-sm-7 col-md-pull-5">
        <div class="keski-news-home infobox" id="keskiNews">
            <h2 class="news-section-title"><?= $this->transEsc("news_section_title") ?></h2>
            <ul id="keskiNewsUl"></ul>
            <p class="news-page-link-container">
                <span class="news-date" aria-hidden="true"></span>
                <a class="news-page-link" href="/Content/uutiset">
                        <span class="news-li-title"><?= $this->transEsc("to_news_archive") ?>
                            <i class="fa fa-arrow-circle-o-right"></i></span>
                </a>
            </p>
        </div>
    </div>
</div>
<!-- News modal -->
<div class="modal fade" id="newsModal" tabindex="-1" role="dialog" aria-labelledby="newsModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="newsModalTitle"></h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div id="newsModalBody" class="modal-body">
                <div id="newsDescription"></div>
                <div id="newsImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary close-news-modal" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
</div>
<!-- END of: finna - search/home/home-1.phtml -->