<!-- Homepage events -->
<div class="events-front-page">
    <h2 class="title-underlined-wide events-section-title"></h2>
    <div class="events-container" id="keskiEvents">
        <ul id="keskiEventsUl">
            <li class="event-li no-matching-events" style="display: none">
                <div class="no-matching-events-div">
                </div>
            </li>
        </ul>
        <div class="loader">Loading...</div>
    </div>
    <div class="news-page-link-container">
            <a role="menuitem" href="/Content/tapahtumat" class="news-page-link btn btn-primary">
                <span class="news-archive-text">
                    <?= $this->transEsc("to_events_page") ?>
                </span>
            </a>
    </div>
</div>
<!-- Events modal -->
<div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="eventModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div class="event-modal-header-text"></div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div id="eventModalBody" class="modal-body">
                <div id="eventDescription"></div>
                <div class="event-modal-location-container">
                    <div class="event-location-info-box"></div>
                    <div id="mapRow" class="">
                        <div id="eventMapContainer" class=""></div>
                    </div>
                </div>
                <div id="eventImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary close-event-modal" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
</div>
