<div class="row" role="navigation" aria-label="<?=$this->transEsc('Footer navigation')?>">
        <div class="col-sm-3">
         <h2 class="footer-list-title" aria-hidden="true"><strong><?=$this->transEsc('About')?></strong></h2>
            <ul title="<?=$this->transEsc('About')?>">
              <li><a href="<?=$this->url('content-page', ['page' => 'kayttosaannot'])?>"><?=$this->transEsc('käyttösäännöt')?></a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'accessibility-statement'])?>"><?=$this->transEsc('saavutettavuusseloste')?></a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'terms'])?>"><?=$this->transEsc('Terms')?></a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->transEsc('Privacy')?></a></li>
               <?php if ($this->cookieConsent()->isEnabled()): ?>
                <li><a href="#" type="button" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a></li>
              <?php endif; ?>
              <li><a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>"><?=$this->transEsc('About Finna')?></a></li>
            </ul>
        </div>
        <div class="col-sm-3">
            <h2 class="footer-list-title" aria-hidden="true"><strong><?=$this->transEsc('Find More')?></strong></h2>
            <ul title="<?=$this->transEsc('Find More')?>">
                <li>
                <? if ($this->layout()->userLang === "fi"): ?>
                <a href="https://www.kirjastot.fi/kysy" target="_blank">Kysy kirjastonhoitajalta</a>
                <? endif; ?>

                <? if ($this->layout()->userLang === "en-gb"): ?>
                <a href="https://www.libraries.fi/ask" target="_blank">Ask a Librarian</a>
                <? endif; ?>
                </li>

                <li>
                <? if ($this->layout()->userLang === "fi"): ?>
                <a href="https://finna.fi/?lng=fi" target="_blank">Finna.fi-hakupalvelut</a>
                <? endif; ?>

                <? if ($this->layout()->userLang === "en-gb"): ?>
                <a href="https://finna.fi/?lng=en-gb" target="_blank">Finna.fi-search service</a>
                <? endif; ?>
                </li>
                <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
                <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
                <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
            </ul>
        </div>
        <div class="col-sm-3">
            <h2 class="footer-list-title" aria-hidden="true"><strong><?=$this->transEsc('footer_header_need_help')?></strong></h2>
            <ul title="<?=$this->transEsc('footer_header_need_help')?>">
                <li><a href="<?=$this->url('content-page', ['page' => 'help_opac'])?>" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Help')?></a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'hakuohje'])?>" title="<?=$this->transEsc('search_help')?>"><?=$this->transEsc('search_help')?></a></li>
                <li><a href="/Content/kirjastot"><?=$this->transEsc('footer_kirjastot')?></a></li>
                <li><a class="modal-link" href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc('Feedback')?></a></li>
            </ul>
        </div>
        <div class="col-sm-3" aria-hidden="true">
            <div class="footer-logo-container">
                <img src="<?=$this->imageLink('Keski-kirjastot_vaakalogo_nega_rgb2.png')?>" alt="Keski-kirjastot logo" />
            </div>
            <div class="footer-logo-container">
             <img src="<?=$this->imageLink('yleisten-kirjastojen-tunnus-fi-sv-en-rinnakkain-nega.png')?>" alt="Yleisten kirjastojen tunnus" title="" />
            </div>

            <div class="footer-logo-container">
                <a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>" title="<?=$this->escapeHtmlAttr($this->translate('About Finna'))?>">
                    <img src="<?=$this->imageLink('powered-by-finna_fi.png')?>" alt="Finna-logo" />
                </a>
            </div>
            <div class="footer-logo-container">
                <a href="https://vufind.org/" title="<?=$this->escapeHtmlAttr($this->translate('About VuFind'))?>">
                 <img src="<?=$this->imageLink('vufind-logo.png')?>" alt="Vufind logo" />
                </a>
            </div>
        </div>
    </div>
</div>
