<? $this->headTitle('Tietoa mobiilitehtävistä'); $this->content()->setHeading('Tietoa mobiilitehtävistä'); ?>
<div class="header">
	<div id="header-container">
		<p>
			<a href="<?= $this->url('content-page', [
   	'page' => 'tehtavat',
   ]) ?>">Takaisin mobiilitehtäviin</a><br />
		</p>
	</div>
</div>
<div id="tietoa" class="ohje">
	<h4>Yleistä</h4>
	<p>
	Mobiilitehtävät pohjautuvat KRSTL:ään, joka on alkujaan Oulun kaupunginkirjastoa varten luotu sovellus. Alkuperäisen sovelluksen on kirjoittanut Sampo Lehtinen. <br /><br />
	Oulun kaupunginkirjasto on julkaissut KRSTL:n MIT-lisenssillä käytettäväksi. GitHub-projekti löytyy <a href="https://github.com/tsjl/KRSTL">täältä</a>. Myös Tampereen kaupunginkirjasto on tehnyt oman <a href="http://www.tampere.fi/kirjasto/tiedonhaku/about.html">MIT-lisensoidun KRSTL-sovelluksen</a>, jonka <a href="https://github.com/Tampereen-kaupunginkirjasto/">GitHub</a> kannattaa käydä katsomassa. MIT-lisenssi ei koske kirjastojen värimalleja eikä logoja.
	<br /><br />
	Keski-kirjastojen käyttöön sovelluksen on muokannut Joonas Viljakainen. 
	</p>
	<h4>Lisätietoja</h4>
	<p>Jyväskylän kaupunginkirjasto<br />
		Juha Hälinen <br />
		Verkkopalvelusuunnittelija</p>
	</div>
	<div id="koepaikka">
</div>
<div class="footer">
	<p>
		Kysymyslomake on kehitetty <a href="https://github.com/tsjl/KRSTL" target="_blank">KRSTL</a>:stä. Lähdekoodi on käytettävissä MIT-lisenssillä. Vastauksia ei säilytetä missään, eikä sivu kerää käyttäjästä tietoja.<a href="http://s.iki.fi/krstl"> </a>
		<br />
	</p>
</div>
