<? $this->headTitle($this->transEsc("news_archive")); ?>
<div class="news-page">
    <div class="keski-news-archive" id="keskiNews">
        <h1 class="news-section-title title-underlined-wide"><?= $this->transEsc("all_news") ?></h1>
        <div class="loader">Loading...</div>
        <ul id="keskiNewsUl" class="row"></ul>
    </div>
</div>
<!-- News modal -->
<div class="modal fade" id="newsModal" tabindex="-1" role="dialog" aria-labelledby="newsModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="newsModalTitle"></h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div id="newsModalBody" class="modal-body">
                <div id="newsDescription"></div>
                <div id="newsImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary close-news-modal" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
</div>
