<? $this->headTitle($this->transEsc("news_archive")); ?>
<div class="news-page">
    <div class="keski-news-archive" id="keskiNews">
        <h1 class="news-section-title"><?= $this->transEsc("all_news") ?></h1>
        <div class="loader">Loading...</div>
        <ul id="keskiNewsUl" class="row"></ul>
    </div>
</div>
<!-- News modal -->
<div class="modal fade" id="newsModal" tabindex="-1" aria-labelledby="newsModalTitle">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="newsModalTitle"></h1>
                <button type="button" class="btn-close close" data-bs-dismiss="modal" aria-label="<?= $this->transEsc("modal_close") ?>"></button>
            </div>
            <div id="newsModalBody" class="modal-body">
                <div id="newsDescription"></div>
                <div id="newsImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><?= $this->transEsc("modal_close") ?></button>
            </div>
        </div>
    </div>
</div>