<!-- START of: finna - search/browsebar.phtml -->
<?php
// PageUrl is added to category search links so that they may work in other pages than the front as well.
$pageUrl = 'https://' . $_SERVER['HTTP_HOST'] . '/';
?>


<div class="browsebar">
    <div class="container">
    
        
        <nav class="navbar">
            <span class="browsebar-title"><?=$this->translate('browsebar-title')?></span> 
            <div class="wrapper resize-drag nav-wrapper">
                <ul class="nav navbar-nav nav-ul">
                    <li><a href="<? echo $pageUrl ?>Search/Results?lookfor=&type=AllFields&filter%5b%5d=first_indexed%3A%22%5bNOW-1MONTHS+TO+NOW%5d%22&filter%5B%5D=%7Ebuilding%3A%220%2FKeski%2F%22&type=AllFields&sort=main_date_str+desc"><i class="fa fa-diamond" aria-hidden="true"></i> <?=$this->transEsc("browsebar_uutuudet")?></a></li>
                    <li><a href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=%7Eformat%3A%221%2FBook%2FBook%2F%22&filter%5B%5D=first_indexed%3A%22%5bNOW-1MONTHS+TO+NOW%5d%22&filter%5B%5D=%7Ebuilding%3A%220%2FKeski%2F%22&type=AllFields"><i class="fa fa-book" aria-hidden="true"></i> <?=$this->transEsc("browsebar_kirjat")?></a></li>
                    <li><a href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=first_indexed%3A%22%5BNOW-1MONTHS+TO+NOW%5D%22&filter%5B%5D=~major_genre_str_mv%3A%22music%22&filter%5B%5D=%7Ebuilding%3A%220%2FKeski%2F%22&type=AllFields"><i class="fa fa-music" aria-hidden="true"></i> <?=$this->transEsc("browsebar_musiikki")?></a></li>
                    <li><a href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=first_indexed%3A%22%5BNOW-1MONTHS+TO+NOW%5D%22&filter%5B%5D=~format%3A%220%2FVideo%2F%22&filter%5B%5D=%7Ebuilding%3A%220%2FKeski%2F%22&type=AllFields"><i class="fa fa-film" aria-hidden="true"></i> <?=$this->transEsc("browsebar_elokuvat")?></a></li>
                    <li><a href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=first_indexed%3A%22%5BNOW-3MONTHS+TO+NOW%5D%22&filter%5B%5D=~genre_facet%3A%22Lautapelit%22&filter%5B%5D=~genre_facet%3A%22Konsolipelit%22&filter%5B%5D=%7Ebuilding%3A%220%2FKeski%2F%22&type=AllFields"><i class="fa fa-gamepad" aria-hidden="true"></i> <?=$this->transEsc("browsebar_pelit")?></a></li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<!-- END of: finna - search/browsebar.phtml -->