<!-- START of: finna - search/home/home-1.phtml -->
<div class="row home-first-row">
    <div class="col-sm-5 col-md-push-7">
        <?= $this->organisationInfo() ?>
        <!-- Hidden on mobile -->
        <div class="d-none d-md-block mb-3">
            <a href="https://www.cineast.fi/" target="_blank"> 
                <img src="<?=$this->imageLink('Cineast.fi.png');?>" width="100%" alt="Cineast-elokuvapalvelu">
            </a>
        </div>
    </div>
    <div class="col-sm-7 col-md-pull-5 order-sm-first">
        <section class="keski-news-home" id="keskiNews" aria-labelledby="keskiNewsTitle">
            <h2 id="keskiNewsTitle" class="title-underlined-wide news-section-title"><?= $this->transEsc("news_section_title") ?></h2>
            <div class="loader">Loading...</div>
            <ul id="keskiNewsUl"></ul>
            <div class="news-page-link-container">
                <a role="menuitem" href="/Content/uutiset" class="news-page-link btn btn-primary">
                    <span class="news-archive-text">
                        <?= $this->transEsc("to_news_archive") ?>
                   </span>
                </a>
            </div>
        </section>
    </div>
</div>
<!-- News modal -->
<div class="modal fade" id="newsModal" tabindex="-1" aria-labelledby="newsModalTitle">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title" id="newsModalTitle"></h1>
                <button type="button" class="btn-close close" data-bs-dismiss="modal" aria-label="<?= $this->transEsc("modal_close") ?>"></button>
            </div>
            <div id="newsModalBody" class="modal-body">
                <div id="newsDescription"></div>
                <div id="newsImageContainer"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><?= $this->transEsc("modal_close") ?></button>
            </div>
        </div>
    </div>
</div>
<!-- END of: finna - search/home/home-1.phtml -->
