<!-- START of: finna - search/browsebar.phtml -->
<?php
// PageUrl is added to category search links so that they may work in other pages than the front as well.
$pageUrl = 'https://' . $_SERVER['HTTP_HOST'] . '/';
?>
<div class="browsebar">
    <div class="container">
        <nav class="navbar">
            <span class="browsebar-title"><?=$this->translate('Browse')?></span>
            <div class="wrapper resize-drag nav-wrapper">
                <ul class="nav navbar-nav nav-ul">
                    <li><a class="iconlabel format-1bookbook" href="<? echo $pageUrl ?>Search/Results?lookfor=&type=AllFields&filter%5b%5d=first_indexed%3A%22%5bNOW-1MONTHS+TO+NOW%5d%22"><?=$this->transEsc("browsebar_uutuudet")?></a></li>
                    <li><a class="iconlabel format-1bookbook" href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=%7Eformat%3A%221%2FBook%2FBook%2F%22&type=AllFields&sort=main_date_str+desc"><?=$this->transEsc("browsebar_kirjat")?></a></li>
                    <li><a class="iconlabel format-0note" href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=%7Eformat%3A%221%2FSound%2FCD%2F%22&filter%5B%5D=%7Eformat%3A%220%2FMusicalScore%2F%22&type=AllFields&sort=main_date_str+desc"><?=$this->transEsc("browsebar_musiikki")?></a></li>
                    <li><a class="iconlabel format-1videovideo" href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=%7Eformat%3A%220%2FVideo%2F%22&type=AllFields&sort=main_date_str+desc"><?=$this->transEsc("browsebar_elokuvat")?></a></li>
                    <li><a class="iconlabel format-1soundrecord" href="<? echo $pageUrl ?>Search/Results?sort=main_date_str+desc&limit=0&filter%5B%5D=%7Eformat%3A%221%2FOther%2FCDROM%2F%22&filter%5B%5D=%7Eformat%3A%220%2FPhysicalObject%2F%22&filter%5B%5D=%7Eformat%3A%221%2FOther%2FElectronic%2F%22&join=AND&bool0%5B%5D=OR&lookfor0%5B%5D=lautapelit&lookfor0%5B%5D=konsolipelit&type0%5B%5D=Subject&type0%5B%5D=Subject"><?=$this->transEsc("browsebar_pelit")?></a></li>
                    <li><a class="iconlabel format-ebook" href="<? echo $pageUrl ?>Search/Results?filter%5B%5D=%7Eformat%3A%221%2FBook%2FeBook%2F%22&filter%5B%5D=%7Eformat%3A%221%2FSound%2FNonmusicalRecording%2F%22&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=&type0%5B%5D=AllFields&sort=main_date_str+desc"><?=$this->transEsc("browsebar_ematerial")?></a></li>
                </ul>
            </div>
        </nav>
    </div>
</div>
<!-- END of: finna - search/browsebar.phtml -->