<!-- START of: CUSTOM finna - Helpers/cookie-consent.phtml -->
<div class="container-fluid cookie-consent cookie-consent-text">
    <?=$this->translate('cookie_consent_html',
    ['%%link%%' => $this->url('content-page', ['page' => 'privacy']) . '#cookies'])?>
    <button class="btn btn-primary cookie-consent-dismiss cookie-consent-button"
        aria-label="<?=$this->transEsc('Accept cookies')?>">
        <?=$this->transEsc('OK')?>
    </button>
</div>
<!-- END of: finna - Helpers/cookie-consent.phtml -->
