<?php
$url =  "//{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}";
$escaped_url = htmlspecialchars( $url, ENT_QUOTES, 'UTF-8' );
?>
<script>
    function checkIfPageExists(string) {
        try {
            var request = new XMLHttpRequest();
            request.open('GET', string, true);
            request.onreadystatechange = function(){
                if (request.readyState === 4) {
                    if (request.status === 200) {
                        window.location = string;
                        return true;
                    }
                    else {
                        return false;
                    }
                }
            };
            request.send();
        }
        catch(e) {
            return false;
            // Page not found... console.log(e)
        }
    }
    // Parse the url as JS variable, remove duplicated // and possible lang codes.
    var url = '<? echo $escaped_url ?>';
    if (url.indexOf('//') > -1) {
        if (url !== url.replace(/([^:]\/)\/+/g, '$1')) {
            url = url.replace(/([^:]\/)\/+/g, '$1');
        }
    }
    if (url.indexOf('?lng=fi') > -1) {
        url = url.replace('?lng=fi', '');
    }
    else if(url.indexOf('?lng=en-gb') > -1) {
        url = url.replace('?lng=en-gb', '');
    }
    // Re-direct to /Content/Foo if using lowercase /content/
    if (locationUrl.indexOf('/content/') > -1) {
        window.location = locationUrl.replace('/content/', '/Content/');
    }
    var ulrWithContent = url.substring(0, url.lastIndexOf('/')) +
        '/Content' + url.substring(url.lastIndexOf('/'));
    // Check if the /Content/ page exists, if so, redirect-to it.
    checkIfPageExists(ulrWithContent);
</script>
<?php
  $this->layout()->finnaMainHeader = '<div><h3 class="finna-main-header">' . $this->transEsc($this->message) . '</h3></div>';
  $this->headTitle($this->transEsc($this->message));
?>
<div class="content-404">
  <?php if (isset($this->reason) && $this->reason): ?><!-- <p><b><?=$this->transEsc('Message')?>:</b> <?=$this->transEsc($this->reason)?></p> --><?php endif; ?>
  <h4><?=$this->transEsc('404_details_text');?></h4>
  <ul class="links-404 list-bullets">
    <li><a href="<?=$this->url('home');?>"><?=$this->transEsc('404_home');?></a></li>
  </ul>
  <br>
  <p><?=$this->transEsc('404_broken_links');?> <a href="<?=$this->url('feedback-home');?>"><?=$this->transEsc('404_feedback');?>.</a></p>
</div>
