<!-- START of: finna - footer.phtml -->
<div class="footer-container">
  <div class="footer-column">
    <h4><strong><?=$this->transEsc('About')?></strong></h4>
    <ul>
      <li><a href="<?=$this->url('content-page', ['page' => 'about'])?>"><?=$this->transEsc('About Us')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>"><?=$this->transEsc('What is Finna')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'terms'])?>"><?=$this->transEsc('Terms')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->transEsc('Privacy')?></a></li>
    </ul>
  </div>
  <div class="footer-column">
     <h4><strong><?=$this->transEsc('Need Help?')?></strong></h4>
    <ul>
      <li><a href="<?=$this->url('content-page', ['page' => 'help'])?>" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Help')?></a></li>
      <li><a href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc('Feedback')?></a></li>
    </ul>
  </div>
  <div class="footer-column">
  </div>
  <div class="footer-column">
  <a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>" title="<?=$this->escapeHtmlAttr($this->translate('About Finna'))?>">
      <img src="<?=$this->imageLink('powered-by-finna_' . $this->layout()->userLang . '-black.png')?>" alt=""/>
      <span class="sr-only"><?=$this->transEsc('About Finna')?></span>
    </a>
    <br><br>
    <a href="https://vufind.org/" title="<?=$this->escapeHtmlAttr($this->translate('About VuFind'))?>">
      <img src="<?=$this->imageLink('vufind-logo-black.png')?>" alt=""/>
      <span class="sr-only"><?=$this->transEsc('About VuFind')?></span>
    </a>
  </div>
</div>
<hr>
<div class="footer-container">
  <div class="footer-column">
  </div>
  <div class="footer-column">
  </div>
</div>
<!-- https://vaski.finna.fi/ has a nice footer; to DO: copy? + https://vaski.finna.fi/Content/help -->
<!-- END of: finna - footer.phtml -->
