<!-- START of: finna - footer.phtml -->
<div class="footer-main-container row">
  <div class="footer-left-side">
    <img alt="" class="sr-hidden" src="/keski/themes/custom/images/tausta_footer.png">
  </div>

  <div class="footer-container row">
      <ul class="footer-links">
        <li>
          <a href="<?=$this->url('content-page', ['page' => 'terms'])?>">
          <?=$this->transEsc('Terms')?></a>
        </li>
        <li>
          <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>">
          <?=$this->transEsc('Privacy') ?></a> & <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>#cookies">
            <?=$this->transEsc('cookies') ?></a>
        </li>
        <li>
          <a href="<?=$this->url('content-page', ['page' => 'accessibility-statement'])?>">
          <?=$this->transEsc('accessibility_statement')?></a>
        </li>
      </ul>
  </div>
  <div class="footer-container row footer-logo-row">
  <ul class="footer-links">
        <li class="foot-logo-link">
          <a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>" title="<?=$this->escapeHtmlAttr($this->translate('About Finna'))?>">
            <img src="<?=$this->imageLink('powered-by-finna_' . $this->layout()->userLang . '-black.png')?>" alt=""/>
            <span class="sr-only"><?=$this->transEsc('About Finna')?></span>
          </a>
        </li>
        <li class="foot-logo-link">
          <a href="https://vufind.org/" title="<?=$this->escapeHtmlAttr($this->translate('About VuFind'))?>">
            <img src="<?=$this->imageLink('vufind-logo-black.png')?>" alt=""/>
            <span class="sr-only"><?=$this->transEsc('About VuFind')?></span>
          </a>
        </li>
        <li class="foot-logo-link">
          <a href="http://www.kirjastot.fi/" title="<?=$this->transEsc('source_KIFI')?>">
          <img src="https://vaski.finna.fi/themes/custom/images/kifi-logo.png?_=1516782463" alt="">
          <span class="sr-only"><?=$this->transEsc('source_KIFI')?></span>
        </a>
        </li>
      </ul>
  </div>
  <div class="footer-right-side">
    <img alt="" class="sr-hidden" src="/keski/themes/custom/images/tausta_footer.png">
  </div>
</div>
<!-- https://vaski.finna.fi/ has a nice footer; to DO: copy? + https://vaski.finna.fi/Content/help -->
<!-- END of: finna - footer.phtml -->
