<!-- START of: finna - navibar.phtml -->
<?php
// Function for logging to browser console. TO DO: Find a better place for it.
function consoleLog($data) {
    $output = $data;
    if (is_array($output))
        $output = implode(',', $output);
    echo "<script>console.log('Debug Objects: " . $output . "' );</script>";
}

// Function to check the string is ends
// with given substring or not
function endsWith($string, $endString)
{
    $len = strlen($endString);
    if ($len == 0) {
        return true;
    }
    return (substr($string, -$len) === $endString);
}
?>

<?php $account = $this->auth()->getManager(); ?>
<div role="navigation" class="finna-navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-collapse" aria-label="<?=$this->escapeHtmlAttr($this->translate('Main Navigation')) ?>" aria-expanded="false">
      <i class="fa fa-bars" aria-hidden="true"></i>
      <i class="fa fa-times" aria-hidden="true"></i>
    </button>
    <?php if ($this->resolver('navibar-logo.phtml')): ?><a title="<?= $this->translate('homepage') ?>" class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->render('navibar-logo.phtml')?>
    <span class="sr-only">><?= $this->translate('homepage') ?></span>
    </a><?php endif ?>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <ul role="menubar" class="nav navbar-nav navbar-main">
        <?php foreach ($this->navibar()->getMenuItems($this->layout()->userLang) as $key => $val): ?>
          <?php if (count($val['items']) > 1): ?>
            <li class="dropdown" id="<?= $val['label'] ?>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <?php
                  if ($val['label'] == 'menu_Vinkit') {
                      echo '<i class="fa fa-archive"></i> ';
                  } ?>
                  <i class="fa fa-nav-<?=$val['label'] ?>" aria-hidden="true"></i><?= $this->transEsc($val['label']) ?> <b class="caret" aria-hidden="true"></b></a>
              <ul role="group" class="dropdown-menu" aria-labelledby="<?= $val['label'] ?>">
                <?php foreach ($val['items'] as $itemKey => $itemVal): ?>
                <?php
                  if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
                    continue;
                  }
                  $url = $itemUrl['url'];
                  $target = !empty($itemUrl['target']) ? $itemUrl['target'] : null;
                  $label = $itemVal['label'];
                  $desc = !empty($itemVal['desc']) ? $itemVal['desc'] : null;
                ?>
                <li>
                  <a  role="menuitem" <?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?=$this->escapeHtmlAttr($url)?>">
                    <div><?= $this->transEsc($label) ?></div>
                    <?php if ($desc): ?>
                      <div class="description" role="note"><?= $this->transEsc($desc) ?></div>
                    <?php endif; ?>
                  </a>
                </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php else:
            $itemVal = $val['items'][0];
            if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
              continue;
            }
            $url = $itemUrl['url'];
            $target = $itemUrl['target'] ?? null;
            $label = $itemVal['label'];
            $menuIcon = '';
            if (endsWith($url, '/kirjastot')) {
                $menuIcon = '<i class="fa fa-building" aria-hidden="true"></i> ';
            }
            else if (endsWith($url, '/info')) {
                $menuIcon = '<i class="fa fa-info-circle" aria-hidden="true"></i> ';
            }
            else if (endsWith($url, '/ekirjasto')) {
                $menuIcon = '<i class="fa fa-globe" aria-hidden="true"></i> ';
            }
            // Feedback and menus with sub links are constructed later.
          ?>
            <li><a <?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?= $url ?>"><?= $menuIcon ?><i class="fa fa-nav-<?=$label ?>" aria-hidden="true"></i><?= $this->transEsc($label) ?></a></li>
          <?php endif; ?>
        <?php endforeach; ?>
        <?php $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a role="menuitem" id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <span class="sr-only"><?=$this->transEsc('items')?></span></a>
          </li>
        <?php endif; ?>
        <?php if ($this->feedback()->tabEnabled()): ?>
          <li>
          <a  role="menuitem" id="feedback-link" href="<?=$this->url('feedback-home') ?>"> <i class="fa fa-comment" aria-hidden="true"></i>
          <?=$this->transEsc("Feedback")?></a>
        </li>
        <?php endif; ?>
        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
        <li class="dropdown">
          <form method="post" name="themeForm" id="themeForm">
            <input type="hidden" name="ui"/>
          </form>
          <a role="menuitem" href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
          <ul role="menu" class="dropdown-menu">
            <?php foreach ($this->layout()->themeOptions as $current): ?>
              <li <?=$current['selected'] ? 'class="active"' : ''?>><a role="menuitem" href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
            <?php endforeach; ?>
          </ul>
        </li>
        <?php endif; ?>
        <?php if ($template = $this->content()->findTemplateForLng("content/Additions/header-navibar")): ?>
          <?=$this->render($template)?>
        <?php endif; ?>
        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <?php $i = 1;?>
        <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
          <?php if ($this->layout()->userLang != $langCode):
              // Replace "Suomi" with "Suomeksi" and "English" with "In English".
              $langText = "In English";
              if ($langName == "Finnish") {
                  $langText = "Suomeksi";
              }
              ?>
            <!-- Replaced class lang with lang-selector -->
            <li class="mobile-lang-selector">
              <a role="menuitem" class="preserve-anchor" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>">
              <i class="fa fa-language" aria-hidden="true"></i> 
              <?=$this->displayLanguageOption($langText)?></a>
            </li>
            <?php $i++; ?>
          <?php endif ?>
        <?php endforeach; ?>
      <?php endif; ?>
      </ul>
    <?php //hide login if unavailable ?>
    <?php if (is_object($account) && $account->loginEnabled()): ?>
      <?php $user = $account->isLoggedIn(); ?>
      <?php if (!$user): ?>
        <ul role="menu" class="nav navbar-nav nav-login">
          <li class="nav-login" id="loginOptions-navi"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
          <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a role="menuitem" href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-user" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
          <?php else: ?>
            <?php if ($this->templateDir === 'myresearch' && $this->templateName === 'login'): ?>
              <div>
                <a class="btn btn-primary btn-uppercase"><i class="fa fa-user fa-lg" aria-hidden="true"></i><span  class="login-text"><?=$this->transEsc("Login")?></span></a>
              </div>
            <?php else: ?>
              <div>
                <a href="<?=$this->url('myresearch-userlogin')?>" class="btn btn-primary btn-uppercase" data-lightbox data-lightbox-onclose="window.location.href='<?=$this->escapeHtmlAttr($this->url('myresearch-home')) ?>'"><i class="fa fa-user fa-lg" aria-hidden="true"></i><span class="login-text"><?=$this->transEsc("Login")?></span></a>
              </div>
            <?php endif; ?>
          <?php endif; ?>
          </li>
        </ul>
      <?php endif; ?>
    <?php endif; ?>
    </div>
    <ul role="menubar" aria-label="<?=$this->transEsc('Your Account')?>" class="nav navbar-nav nav-absolute">
      <?php if (is_object($account) && $account->loginEnabled()): ?>
        <?php if ($this->auth()->isLoggedIn()): ?>
          <li class="logoutOptions">
            <a href="#" role="menuitem" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg" aria-hidden="true"></i> <span class="username login-text"><?=$user ? $this->escapeHtml($this->truncate($user->getDisplayName(), 20)) : $this->transEsc("Your Account")?></span><b class="caret"></b></a>
            <ul role="menu" id="my-info-dropdown-menu" class="dropdown-menu">
              <?php if ($user->getLibraryCards()->count() > 0): ?>
                <li>
                  <a role="menuitem" href="<?=$this->url('myresearch-checkedout')?>">
                    <?=$this->transEsc('Checked Out Items')?>
                  </a>
                </li>
                <li>
                  <a role="menuitem" href="<?=$this->url('myresearch-holds')?>">
                    <?=$this->transEsc('Holds and Recalls')?>
                  </a>
                </li>
                <li>
                  <a role="menuitem" href="<?=$this->url('myresearch-fines')?>">
                    <?=$this->transEsc('Fines')?>
                  </a>
                </li>
              <?php endif; ?>
              <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'loginMenu' => 'true', 'label' => 'Library Cards','limit' => 0]);?>
              <li>
                <a role="menuitem" href="<?=$this->url('myresearch-profile')?>">
                  <?=$this->transEsc('Profile')?>
                </a>
              </li>
              <li>
                <a role="menuitem" href="<?=$this->url('search-history')?>?require_login">
                  <?=$this->transEsc('history_saved_searches')?>
                </a>
              </li>
              <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
                <li>
                  <a role ="menuitem" href="<?=$this->url('myresearch-favorites')?>">
                    <?=$this->transEsc('Favorites')?>
                  </a>
                </li>
              <?php endif; ?>
              <li>
                <a role="menuitem" href="<?=$this->url('myresearch-logout')?>" title="<?=$this->transEsc("Log Out")?>"><?=$this->transEsc("Log Out")?><i class="pull-right fa fa-sign-out fa-lg" aria-hidden="true"></i></a>
              </li>
            </ul>
          </li>
          <?php else: ?>
            <!-- NOT LOGGED IN  TO KESKI -->






            
          <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a role="menuitem" href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-user" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
          <?php else: ?>
            <?php if ($this->templateDir === 'myresearch' && $this->templateName === 'login'): ?>
              <div>
                <a class="btn btn-primary btn-uppercase"><i class="fa fa-user fa-lg" aria-hidden="true"></i><span  class="login-text"><?=$this->transEsc("Login")?></span></a>
              </div>
            <?php else: ?>
            <!-- START of: finna - Auth/MultiILS/login.phtml -->
            <?php $account = $this->auth()->getManager(); ?>
            <?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
            <li class="loginOptions">

              <a href="#" role="menuitem" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="loginOptions">
                <i class="fa fa-user fa-lg" aria-hidden="true"></i> <span class="username login-text"><?=$this->transEsc("Login")?></span>
                <b class="caret"></b>
              </a>

                <ul role="menu" id="my-info-dropdown-menu" class=" loginOptions dropdown-menu login-dropdown">

                  <form method="post" class="form-vertical" action="<? echo $this->url('myresearch-home') ?>" name="loginForm" id="loginForm">

 
                    <div class="login-test" style="z-index: 999999">
                      <!-- CARD INPUT -->
                      <label class="pure-material-textfield-outlined">
                          <input id="login_MultiILS_username" autocomplete="username" type="text" name="username" value="" placeholder=" ">
                          <span>Kirjastokortti</span>
                      </label>
                      <!-- PIN INPUT -->
                      <label class="pure-material-textfield-outlined">
                          <input id="login_MultiILS_password" autocomplete="current-password" type="password" name="password" placeholder=" ">
                          <span>PIN</span>
                      </label>
                      <!-- FINNA AUTH -->
                      <input type="hidden" name="auth_method" value="MultiILS">
                      <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>" />
                      <!-- LOGIN BTN -->
                      <input class="btn btn-primary login-btn" type="submit" name="processLogin" value="Kirjaudu">
                    </div>
                  </form>

                    <div class="login-help-links">
                      <p>
                        <a id="login_library_card_register" class="btn btn-link" href="/beta/LibraryCards/Register" style="display: block;">Ilmoittaudu kirjaston asiakkaaksi</a>
                      </p>
                      <p>
                        <a id="login_library_card_recovery" class="btn btn-link" href="/beta/LibraryCards/Recover" style="display: block;">Unohditko salasanasi?</a>
                      </p>
                   </div>





                </ul>
            </li>
            <script>
                //<!--
              setupMultiILSLoginFields({"keski":"password"}, 'login_MultiILS_');
              finna.layout.initSecondaryLoginField({"keski":""}, 'login_MultiILS_');
                //-->

                // Prevent the item from being accidentally closed.
                $(document).on('click', '.open .dropdown-menu', function (e) {
                  e.stopPropagation();
                });

            </script>

        <!-- END of: finna - Auth/MultiILS/login.phtml -->

        <?php endif; ?>

            <?php endif; ?>
          <?php endif; ?>
        </li>


      <?php endif; ?>
    </ul>
      <ul role="menubar" class="nav navbar-nav lang nav-absolute">
        <?php if ($template = $this->content()->findTemplateForLng("content/Additions/header-navibar")): ?>
      <?=$this->render($template)?>
        <?php endif; ?>
        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <?php $i = 1;?>
        <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
          <?php if ($this->layout()->userLang != $langCode):
              // Replace "Suomi" with "Suomeksi" and "English" with "In English".
              $langText = "In English";
              if ($langName == "Finnish") {
                  $langText = "Suomeksi";
              }
              ?>
            <!-- Replaced class lang with lang-selector -->
            <li class="lang-selector">
              <a role="menuitem" class="btn btn-primary lang-btn preserve-anchor" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>">
              <span><i class="fa fa-language" aria-hidden="true"></i> 
              <?=$this->displayLanguageOption($langText)?></span></a>
            </li>
            <?php $i++; ?>
          <?php endif ?>
        <?php endforeach; ?>
      <?php endif; ?>
    </ul>
  <?php endif; ?>
</div>
<!-- END of: finna - navibar.phtml -->
