<!-- START of: finna - footer.phtml -->
<div class="footer-main-container row">
    <div class="footer-left-side">
      <img alt="" class="sr-hidden" src="/keski/themes/custom/images/tausta_footer.png">
    </div>

    <div class="footer-container row">
        <ul class="footer-links">
          <li>
            <a href="<?=$this->url('content-page', ['page' => 'terms'])?>">
<?=$this->transEsc('Terms')?></a>
</li>
<li>
<a href="<?=$this->url('content-page', ['page' => 'privacy'])?>">
<?=$this->transEsc('Privacy') ?></a> & <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>#cookies">
<?=$this->transEsc('cookies') ?></a>
</li>
<li>
<a href="<?=$this->url('content-page', ['page' => 'accessibility-statement'])?>">
<?=$this->transEsc('accessibility_statement')?></a>
</li>
</ul>
</div>
<div class="footer-container row footer-logo-row">
<ul class="footer-links">
<li class="foot-logo-link">
<a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>" title="<?=$this->escapeHtmlAttr($this->translate('About Finna'))?>">
  <img src="<?=$this->imageLink('powered-by-finna_' . $this->layout()->userLang . '-black.png')?>" alt=""/>
  <span class="sr-only"><?=$this->transEsc('About Finna')?></span>
</a>
</li>
<li class="foot-logo-link">
<a href="https://vufind.org/" title="<?=$this->escapeHtmlAttr($this->translate('About VuFind'))?>">
  <img src="<?=$this->imageLink('vufind-logo-black.png')?>" alt=""/>
  <span class="sr-only"><?=$this->transEsc('About VuFind')?></span>
</a>
</li>
<li class="foot-logo-link">
<a href="http://www.kirjastot.fi/" title="<?=$this->transEsc('source_KIFI')?>">
<img src="https://vaski.finna.fi/themes/custom/images/kifi-logo.png?_=1516782463" alt="">
<span class="sr-only"><?=$this->transEsc('source_KIFI')?></span>
</a>
</li>
</ul>
</div>
<div class="footer-right-side">
<img alt="" class="sr-hidden" src="/keski/themes/custom/images/tausta_footer.png">
</div>
</div>

<!-- Smilee service script start -->
<script type="text/javascript" charset="UTF-8" async>
(function () {
var x = document.createElement('script');
x.src = 'https://saas.smilee.fi/assets/javascripts/cobrowse.js';
x.type = 'text/javascript';
x.async = 'true';
x.onload = x.onreadystatechange = function () {
var rs = this.readyState;
if (rs && rs != 'complete' && rs != 'loaded') return;
var lang = 'fin'
if (window.document.documentElement.lang === 'en-gb') {
lang = 'eng'
}
try {
Cobrowse.create({
apiKey: 'bKTIi3M28OVzWtq7f0kYlIu2NA4SoZnn3NmhdSDBPFfUtJMaXrXR1dixD/m36u1LFD4YVQlmWqF9MlyYgHhRogPrzMZU83coPyDACqifgPE=', serverUrl: 'https://saas.smilee.fi',
locale: lang
});
} catch (e) {
console.error('Failed loading Smilee script');
}
};
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(x, s);
})();
</script>
<!-- Smilee service script end -->
